### ISSUE TITLE
Plaster of Paris for real

### ISSUE THREAD

**Issue by anion155** [Aleksey-Terzi/DecorationsTFC#1]
Are you planning to make Gypsum plaster craft as it was in original suggestion post (heat it to 300*K and than smash)?

**Comment by Aleksey-Terzi** [comment]
I thought to implement this but in this case gypsum mortar will not be used if player has flux stone (it is almost always easy to find such stone especially in multiplayer)
So my answer - no, I'm not planning now heating gypsum to 150C before making powder.

Do you have any suggestion regarding this?

**Comment by anion155** [comment]
If finding gypsum is complicated, why making mortar from it must be easy? It doesn't make any sense.
I mean if you have easy access to flux-stone, why would even think about making mortar from gypsum? Gypsum is more valuable at this point, 'cause it's the only way to make Alabaster.
And if don't have too many flux-stones there is no other option, except making mortar from gypsum, and recipe doesn't really matter, if you need it, you'll make it what ever it takes.

**Comment by Aleksey-Terzi** [comment]
My Gypsum Mortar is just projection of real Gypsum Mortar to the TFC world.

In ancient times there were two main mortars: lime mortar (TFC's flux mortar) and gypsum mortar.
As stated in the following article gypsum mortar is easier to make than lime mortar: https://en.wikipedia.org/wiki/Mortar_(masonry)#Ancient_mortar

Producing of lime mortar requires heating of lime to 1000C (which is much higher than for gypsum).

Therefore I think my implementation is resonable for TFC world.

**Comment by anion155** [comment]
Thanks! I didn't read about lime mortar at all.

**Comment by Aleksey-Terzi** [comment]
Thanks for discussion.
Let me know if you have any questions/suggestions (regarding mod or regarding programming for TFC).
