### ISSUE TITLE
Crash with Custom Recipe outputting TFC gems

### ISSUE THREAD

**Issue by Bunsan** [Aleksey-Terzi/DecorationsTFC#2]
As Reported on TFC forums

Using Decorations 1.0.11 with TFC b79.15

I need to report a crash due to your mod conflicting with a custom recipe I've created in minetweaker. The recipe allows a player to take an exquisite gem and convert it into 2 flawless and convert a flawless gem into a normal gem by use of a blue/red steel chisel. The craft shows the proper output, but upon removing the output the client crashes with http://pastebin.com/0As1ajPK

The custom recipe is 
recipes.addShapeless(terrafirmacraft:item.Diamond:2 \* 2, [<terrafirmacraft:item.Blue Steel Chisel>.anyDamage().transformDamage(), ore:gemFlawlessDiamond]); 
Setting the output to vanilla diamonds works as intended.

I even simplified the recipe to
recipes.addShapeless(terrafirmacraft:item.Diamond:2 \* 2, [ore:gemFlawlessDiamond]);
and got the same crash. It is simply the output of the TFC diamond that is the cause of the crash and only when the decorations add-on is present.

This was tested in TFC b79.15 in forge 1272, with fast craft 1.16, minetweaker3 1.7.10-3.0.9C and minetweaker recipe maker 1.7.10-1.1.0.11

Edit: I spoke with Kitty and looked a bit at the code. I can see that the issue is that you overwrite the TFC item, but that it keeps the same unlocalized name. I'm not sure what the output is, but if I do a .giveBack(terrafirmacraft:item.Diamond:3) it outputs a flawless diamond that is not placeable and has unlocalized name null:3.  So I have no idea why it is throwing a fit or what the exact cause is at this point.

**Comment by Aleksey-Terzi** [comment]
This is MineTweaker's bug - it is not properly support "substitution aliases".

Gems items have been added using:

GameRegistry.addSubstitutionAlias("terrafirmacraft:" + TFCItems.GemDiamond.getUnlocalizedName(), GameRegistry.Type.ITEM, -My Extended Item-);

But MineTweaker doesn't support such items.
