### ISSUE TITLE
gregtech 6 immersive engineering crash

### ISSUE THREAD

**Issue by DarylOliver** [Aleksey-Terzi/DecorationsTFC#6]
Hello I've encountered an odd bug where the decorations mod conflicts with immersive engineering and gregtech 6 causing a crash specifically it causing something in immersive engineering to error but heres the odd thing it only does it when gregtech is installed.

if gregtech 6 isn't installed everythings ok and the same is said for when gregtech 6 is installed and immersive engineering isn't and yet when the decorations mod isn't installed both run fine.

here's my crash report I do hope whatever the problem is it can be fixed since I really like your addon gives gems more use I feel

[crash-2016-08-28_19.58.09-client.txt](https://github.com/Aleksey-Terzi/DecorationsTFC/files/441292/crash-2016-08-28_19.58.09-client.txt)

**Comment by Aleksey-Terzi** [comment]
Hi,

Sorry, but I'm not supporting this project anymore.
I suggest to make fork and fix mod by yourself or ask someone who will do this.

Looks like this fork is active: https://github.com/AnodeCathode/DecorationsTFC
